services:
  retellai-mcp:
    image: ghcr.io/vmdy/retellai-mcp-server:latest
    pull_policy: always
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${TRAEFIK_HOST}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt
      - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3010
    environment:
      - RETELL_API_KEY=${RETELL_API_KEY}
      - MCP_AUTH_TOKEN=${MCP_AUTH_TOKEN}
      - TRANSPORT=http
      - PORT=3010
