import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { retellGet, retellPost, retellPatch, retellDelete } from "../services/retell-client.js";
import { CHARACTER_LIMIT } from "../constants.js";
interface AgentSummary { agent_id: string; agent_name?: string; voice_id?: string; language?: string; is_published?: boolean; response_engine?: { type: string }; }
function truncate(t: string): string { return t.length <= CHARACTER_LIMIT ? t : t.slice(0, CHARACTER_LIMIT) + "\n\n... (truncated)"; }
export function registerAgentTools(server: McpServer): void {
  server.registerTool("retell_list_agents", { title: "List Voice Agents", description: "List all voice agents.", inputSchema: {}, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async () => { const { data } = await retellGet<AgentSummary[]>("/list-agents"); const summary = (data ?? []).map((a) => ({ agent_id: a.agent_id, agent_name: a.agent_name ?? "(unnamed)", voice_id: a.voice_id, language: a.language, is_published: a.is_published, engine_type: a.response_engine?.type })); return { content: [{ type: "text", text: truncate(JSON.stringify(summary, null, 2)) }] }; });
  server.registerTool("retell_get_agent", { title: "Get Voice Agent", description: "Get agent config by ID.\n\nArgs:\n  - agent_id (string)", inputSchema: { agent_id: z.string().min(1) }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ agent_id }) => { const { data } = await retellGet(`/get-agent/${agent_id}`); return { content: [{ type: "text", text: truncate(JSON.stringify(data, null, 2)) }] }; });
  server.registerTool("retell_create_agent", { title: "Create Voice Agent", description: "Create a new voice agent.\n\nArgs:\n  - response_engine (object), voice_id (string), agent_name (string?), language (string?), webhook_url (string?), ambient_sound (string?)", inputSchema: { response_engine: z.record(z.unknown()), voice_id: z.string().min(1), agent_name: z.string().optional(), language: z.string().optional(), webhook_url: z.string().url().optional(), ambient_sound: z.string().optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false } }, async ({ response_engine, voice_id, agent_name, language, webhook_url, ambient_sound }) => { const body: Record<string, unknown> = { response_engine, voice_id }; if (agent_name) body.agent_name = agent_name; if (language) body.language = language; if (webhook_url) body.webhook_url = webhook_url; if (ambient_sound) body.ambient_sound = ambient_sound; const { data } = await retellPost("/create-agent", body); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_update_agent", { title: "Update Voice Agent", description: "Update a voice agent.\n\nArgs:\n  - agent_id (string), agent_name (string?), voice_id (string?), language (string?), response_engine (object?), webhook_url (string?), ambient_sound (string?)", inputSchema: { agent_id: z.string().min(1), agent_name: z.string().optional(), voice_id: z.string().optional(), language: z.string().optional(), response_engine: z.record(z.unknown()).optional(), webhook_url: z.string().optional(), ambient_sound: z.string().optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ agent_id, ...fields }) => { const body: Record<string, unknown> = {}; for (const [k, v] of Object.entries(fields)) { if (v !== undefined) body[k] = v; } const { data } = await retellPatch(`/update-agent/${agent_id}`, body); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_delete_agent", { title: "Delete Voice Agent", description: "Delete a voice agent.\n\nArgs:\n  - agent_id (string)", inputSchema: { agent_id: z.string().min(1) }, annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false } }, async ({ agent_id }) => { const { data } = await retellDelete(`/delete-agent/${agent_id}`); return { content: [{ type: "text", text: data ? JSON.stringify(data, null, 2) : "Deleted." }] }; });
  server.registerTool("retell_publish_agent", { title: "Publish Voice Agent", description: "Publish agent version to production.\n\nArgs:\n  - agent_id (string), version_description (string?)", inputSchema: { agent_id: z.string().min(1), version_description: z.string().optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false } }, async ({ agent_id, version_description }) => { const body: Record<string, unknown> = {}; if (version_description) body.version_description = version_description; const { data } = await retellPost(`/publish-agent/${agent_id}`, body); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_get_agent_versions", { title: "Get Agent Versions", description: "Get all published versions.\n\nArgs:\n  - agent_id (string)", inputSchema: { agent_id: z.string().min(1) }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ agent_id }) => { const { data } = await retellGet(`/get-agent-versions/${agent_id}`); return { content: [{ type: "text", text: truncate(JSON.stringify(data, null, 2)) }] }; });
}
