import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { retellGet, retellPost, retellPatch, retellDelete } from "../services/retell-client.js";
import { CHARACTER_LIMIT } from "../constants.js";
function truncate(t: string): string { return t.length <= CHARACTER_LIMIT ? t : t.slice(0, CHARACTER_LIMIT) + "\n\n... (truncated)"; }
export function registerCallTools(server: McpServer): void {
  server.registerTool("retell_create_phone_call", { title: "Create Phone Call", description: "Initiate an outbound phone call.\n\nArgs:\n  - from_number (string, E.164), to_number (string, E.164), override_agent_id (string?), dynamic_variables (object?)", inputSchema: { from_number: z.string().min(1), to_number: z.string().min(1), override_agent_id: z.string().optional(), dynamic_variables: z.record(z.string()).optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true } }, async ({ from_number, to_number, override_agent_id, dynamic_variables }) => { const body: Record<string, unknown> = { from_number, to_number }; if (override_agent_id) body.override_agent_id = override_agent_id; if (dynamic_variables) body.retell_llm_dynamic_variables = dynamic_variables; const { data } = await retellPost("/v2/create-phone-call", body); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_create_web_call", { title: "Create Web Call", description: "Initiate a web-based call.\n\nArgs:\n  - agent_id (string), metadata (object?), dynamic_variables (object?)", inputSchema: { agent_id: z.string().min(1), metadata: z.record(z.unknown()).optional(), dynamic_variables: z.record(z.string()).optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true } }, async ({ agent_id, metadata, dynamic_variables }) => { const body: Record<string, unknown> = { agent_id }; if (metadata) body.metadata = metadata; if (dynamic_variables) body.retell_llm_dynamic_variables = dynamic_variables; const { data } = await retellPost("/v2/create-web-call", body); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_get_call", { title: "Get Call", description: "Get call details/status/transcript.\n\nArgs:\n  - call_id (string)", inputSchema: { call_id: z.string().min(1) }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ call_id }) => { const { data } = await retellGet(`/v2/get-call/${call_id}`); return { content: [{ type: "text", text: truncate(JSON.stringify(data, null, 2)) }] }; });
  server.registerTool("retell_list_calls", { title: "List Calls", description: "List calls with filters.\n\nArgs:\n  - limit (number?, 1-1000), sort_order (string?), filter_criteria (object?)", inputSchema: { limit: z.number().int().min(1).max(1000).default(50), sort_order: z.enum(["ascending", "descending"]).default("descending"), filter_criteria: z.record(z.unknown()).optional() }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ limit, sort_order, filter_criteria }) => { const body: Record<string, unknown> = { limit, sort_order }; if (filter_criteria) body.filter_criteria = filter_criteria; const { data } = await retellPost("/v2/list-calls", body); return { content: [{ type: "text", text: truncate(JSON.stringify(data, null, 2)) }] }; });
  server.registerTool("retell_update_call", { title: "Update Call", description: "Update call metadata.\n\nArgs:\n  - call_id (string), metadata (object?)", inputSchema: { call_id: z.string().min(1), metadata: z.record(z.unknown()).optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ call_id, metadata }) => { const body: Record<string, unknown> = {}; if (metadata) body.metadata = metadata; const { data } = await retellPatch(`/v2/update-call/${call_id}`, body); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_delete_call", { title: "Delete Call", description: "Delete a call record.\n\nArgs:\n  - call_id (string)", inputSchema: { call_id: z.string().min(1) }, annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false } }, async ({ call_id }) => { const { data } = await retellDelete(`/v2/delete-call/${call_id}`); return { content: [{ type: "text", text: data ? JSON.stringify(data, null, 2) : "Deleted." }] }; });
}
