import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { retellGet, retellPost, retellPatch, retellDelete } from "../services/retell-client.js";
import { CHARACTER_LIMIT } from "../constants.js";
function truncate(t: string): string { return t.length <= CHARACTER_LIMIT ? t : t.slice(0, CHARACTER_LIMIT) + "\n\n... (truncated)"; }
export function registerChatAgentTools(server: McpServer): void {
  server.registerTool("retell_list_chat_agents", { title: "List Chat Agents", description: "List all chat agents.", inputSchema: {}, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async () => { const { data } = await retellGet("/list-chat-agents"); return { content: [{ type: "text", text: truncate(JSON.stringify(data, null, 2)) }] }; });
  server.registerTool("retell_get_chat_agent", { title: "Get Chat Agent", description: "Get chat agent config.\n\nArgs:\n  - agent_id (string)", inputSchema: { agent_id: z.string().min(1) }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ agent_id }) => { const { data } = await retellGet(`/get-chat-agent/${agent_id}`); return { content: [{ type: "text", text: truncate(JSON.stringify(data, null, 2)) }] }; });
  server.registerTool("retell_create_chat_agent", { title: "Create Chat Agent", description: "Create a new chat agent.\n\nArgs:\n  - response_engine (object), agent_name (string?), webhook_url (string?)", inputSchema: { response_engine: z.record(z.unknown()), agent_name: z.string().optional(), webhook_url: z.string().url().optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false } }, async ({ response_engine, agent_name, webhook_url }) => { const body: Record<string, unknown> = { response_engine }; if (agent_name) body.agent_name = agent_name; if (webhook_url) body.webhook_url = webhook_url; const { data } = await retellPost("/create-chat-agent", body); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_update_chat_agent", { title: "Update Chat Agent", description: "Update a chat agent.\n\nArgs:\n  - agent_id (string), agent_name (string?), response_engine (object?), webhook_url (string?)", inputSchema: { agent_id: z.string().min(1), agent_name: z.string().optional(), response_engine: z.record(z.unknown()).optional(), webhook_url: z.string().optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ agent_id, ...fields }) => { const body: Record<string, unknown> = {}; for (const [k, v] of Object.entries(fields)) { if (v !== undefined) body[k] = v; } const { data } = await retellPatch(`/update-chat-agent/${agent_id}`, body); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_delete_chat_agent", { title: "Delete Chat Agent", description: "Delete a chat agent.\n\nArgs:\n  - agent_id (string)", inputSchema: { agent_id: z.string().min(1) }, annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false } }, async ({ agent_id }) => { const { data } = await retellDelete(`/delete-chat-agent/${agent_id}`); return { content: [{ type: "text", text: data ? JSON.stringify(data, null, 2) : "Deleted." }] }; });
  server.registerTool("retell_publish_chat_agent", { title: "Publish Chat Agent", description: "Publish chat agent to production.\n\nArgs:\n  - agent_id (string), version_description (string?)", inputSchema: { agent_id: z.string().min(1), version_description: z.string().optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false } }, async ({ agent_id, version_description }) => { const body: Record<string, unknown> = {}; if (version_description) body.version_description = version_description; const { data } = await retellPost(`/publish-chat-agent/${agent_id}`, body); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_get_chat_agent_versions", { title: "Get Chat Agent Versions", description: "Get all published versions.\n\nArgs:\n  - agent_id (string)", inputSchema: { agent_id: z.string().min(1) }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ agent_id }) => { const { data } = await retellGet(`/get-chat-agent-versions/${agent_id}`); return { content: [{ type: "text", text: truncate(JSON.stringify(data, null, 2)) }] }; });
}
