import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { retellGet, retellPost, retellPatch } from "../services/retell-client.js";
import { CHARACTER_LIMIT } from "../constants.js";
function truncate(t: string): string { return t.length <= CHARACTER_LIMIT ? t : t.slice(0, CHARACTER_LIMIT) + "\n\n... (truncated)"; }
export function registerChatTools(server: McpServer): void {
  server.registerTool("retell_create_chat", { title: "Create Chat", description: "Create a new chat session.\n\nArgs:\n  - agent_id (string), metadata (object?), dynamic_variables (object?)", inputSchema: { agent_id: z.string().min(1), metadata: z.record(z.unknown()).optional(), dynamic_variables: z.record(z.string()).optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true } }, async ({ agent_id, metadata, dynamic_variables }) => { const body: Record<string, unknown> = { agent_id }; if (metadata) body.metadata = metadata; if (dynamic_variables) body.retell_llm_dynamic_variables = dynamic_variables; const { data } = await retellPost("/create-chat", body); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_create_outbound_sms", { title: "Create Outbound SMS", description: "Initiate an outbound SMS chat.\n\nArgs:\n  - from_number (string), to_number (string), agent_id (string?), metadata (object?), dynamic_variables (object?)", inputSchema: { from_number: z.string().min(1), to_number: z.string().min(1), agent_id: z.string().optional(), metadata: z.record(z.unknown()).optional(), dynamic_variables: z.record(z.string()).optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true } }, async ({ from_number, to_number, agent_id, metadata, dynamic_variables }) => { const body: Record<string, unknown> = { from_number, to_number }; if (agent_id) body.agent_id = agent_id; if (metadata) body.metadata = metadata; if (dynamic_variables) body.retell_llm_dynamic_variables = dynamic_variables; const { data } = await retellPost("/create-sms-chat", body); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_get_chat", { title: "Get Chat", description: "Get chat session details.\n\nArgs:\n  - chat_id (string)", inputSchema: { chat_id: z.string().min(1) }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ chat_id }) => { const { data } = await retellGet(`/get-chat/${chat_id}`); return { content: [{ type: "text", text: truncate(JSON.stringify(data, null, 2)) }] }; });
  server.registerTool("retell_create_chat_completion", { title: "Create Chat Completion", description: "Send a message and get agent response.\n\nArgs:\n  - chat_id (string), content (string)", inputSchema: { chat_id: z.string().min(1), content: z.string().min(1) }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true } }, async ({ chat_id, content }) => { const { data } = await retellPost(`/create-chat-completion/${chat_id}`, { content }); return { content: [{ type: "text", text: truncate(JSON.stringify(data, null, 2)) }] }; });
  server.registerTool("retell_list_chats", { title: "List Chats", description: "List chat sessions.", inputSchema: { limit: z.number().int().min(1).max(1000).default(50), sort_order: z.enum(["ascending", "descending"]).default("descending"), filter_criteria: z.record(z.unknown()).optional() }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async () => { const { data } = await retellGet("/list-chat"); return { content: [{ type: "text", text: truncate(JSON.stringify(data, null, 2)) }] }; });
  server.registerTool("retell_update_chat", { title: "Update Chat", description: "Update chat metadata.\n\nArgs:\n  - chat_id (string), metadata (object?)", inputSchema: { chat_id: z.string().min(1), metadata: z.record(z.unknown()).optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ chat_id, metadata }) => { const body: Record<string, unknown> = {}; if (metadata) body.metadata = metadata; const { data } = await retellPatch(`/update-chat/${chat_id}`, body); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_end_chat", { title: "End Chat", description: "End an active chat.\n\nArgs:\n  - chat_id (string)", inputSchema: { chat_id: z.string().min(1) }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ chat_id }) => { const { data } = await retellPatch(`/end-chat/${chat_id}`, {}); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
}
