import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { retellGet, retellPost, retellPatch, retellDelete } from "../services/retell-client.js";
import { CHARACTER_LIMIT } from "../constants.js";
function truncate(t: string): string { return t.length <= CHARACTER_LIMIT ? t : t.slice(0, CHARACTER_LIMIT) + "\n\n... (truncated)"; }
export function registerConversationFlowTools(server: McpServer): void {
  server.registerTool("retell_list_conversation_flows", { title: "List Conversation Flows", description: "List all conversation flow response engines.", inputSchema: {}, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async () => { const { data } = await retellGet("/list-conversation-flows"); return { content: [{ type: "text", text: truncate(JSON.stringify(data, null, 2)) }] }; });
  server.registerTool("retell_get_conversation_flow", { title: "Get Conversation Flow", description: "Get full configuration of a conversation flow.\n\nArgs:\n  - conversation_flow_id (string)", inputSchema: { conversation_flow_id: z.string().min(1) }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ conversation_flow_id }) => { const { data } = await retellGet(`/get-conversation-flow/${conversation_flow_id}`); return { content: [{ type: "text", text: truncate(JSON.stringify(data, null, 2)) }] }; });
  server.registerTool("retell_create_conversation_flow", { title: "Create Conversation Flow", description: "Create a new conversation flow.\n\nArgs:\n  - nodes (array), edges (array), model (string?)", inputSchema: { nodes: z.array(z.record(z.unknown())).min(1), edges: z.array(z.record(z.unknown())), model: z.string().optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false } }, async ({ nodes, edges, model }) => { const body: Record<string, unknown> = { nodes, edges }; if (model) body.model = model; const { data } = await retellPost("/create-conversation-flow", body); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_update_conversation_flow", { title: "Update Conversation Flow", description: "Update a conversation flow.\n\nArgs:\n  - conversation_flow_id (string), nodes (array?), edges (array?), model (string?)", inputSchema: { conversation_flow_id: z.string().min(1), nodes: z.array(z.record(z.unknown())).optional(), edges: z.array(z.record(z.unknown())).optional(), model: z.string().optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ conversation_flow_id, nodes, edges, model }) => { const body: Record<string, unknown> = {}; if (nodes) body.nodes = nodes; if (edges) body.edges = edges; if (model) body.model = model; const { data } = await retellPatch(`/update-conversation-flow/${conversation_flow_id}`, body); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_delete_conversation_flow", { title: "Delete Conversation Flow", description: "Delete a conversation flow.\n\nArgs:\n  - conversation_flow_id (string)", inputSchema: { conversation_flow_id: z.string().min(1) }, annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false } }, async ({ conversation_flow_id }) => { const { data } = await retellDelete(`/delete-conversation-flow/${conversation_flow_id}`); return { content: [{ type: "text", text: data ? JSON.stringify(data, null, 2) : "Deleted." }] }; });
}
