import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { retellGet, retellPost, retellPatch, retellDelete } from "../services/retell-client.js";
import { CHARACTER_LIMIT } from "../constants.js";
function truncate(t: string): string { return t.length <= CHARACTER_LIMIT ? t : t.slice(0, CHARACTER_LIMIT) + "\n\n... (truncated)"; }
export function registerFlowComponentTools(server: McpServer): void {
  server.registerTool("retell_list_flow_components", { title: "List Flow Components", description: "List all reusable conversation flow components.", inputSchema: {}, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async () => { const { data } = await retellGet("/list-conversation-flow-components"); return { content: [{ type: "text", text: truncate(JSON.stringify(data, null, 2)) }] }; });
  server.registerTool("retell_get_flow_component", { title: "Get Flow Component", description: "Get a specific flow component.\n\nArgs:\n  - component_id (string)", inputSchema: { component_id: z.string().min(1) }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ component_id }) => { const { data } = await retellGet(`/get-conversation-flow-component/${component_id}`); return { content: [{ type: "text", text: truncate(JSON.stringify(data, null, 2)) }] }; });
  server.registerTool("retell_create_flow_component", { title: "Create Flow Component", description: "Create a new flow component.\n\nArgs:\n  - nodes (array), edges (array), name (string?)", inputSchema: { nodes: z.array(z.record(z.unknown())).min(1), edges: z.array(z.record(z.unknown())), name: z.string().optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false } }, async ({ nodes, edges, name }) => { const body: Record<string, unknown> = { nodes, edges }; if (name) body.name = name; const { data } = await retellPost("/create-conversation-flow-component", body); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_update_flow_component", { title: "Update Flow Component", description: "Update a flow component.\n\nArgs:\n  - component_id (string), nodes (array?), edges (array?), name (string?)", inputSchema: { component_id: z.string().min(1), nodes: z.array(z.record(z.unknown())).optional(), edges: z.array(z.record(z.unknown())).optional(), name: z.string().optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ component_id, nodes, edges, name }) => { const body: Record<string, unknown> = {}; if (nodes) body.nodes = nodes; if (edges) body.edges = edges; if (name) body.name = name; const { data } = await retellPatch(`/update-conversation-flow-component/${component_id}`, body); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_delete_flow_component", { title: "Delete Flow Component", description: "Delete a flow component.\n\nArgs:\n  - component_id (string)", inputSchema: { component_id: z.string().min(1) }, annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false } }, async ({ component_id }) => { const { data } = await retellDelete(`/delete-conversation-flow-component/${component_id}`); return { content: [{ type: "text", text: data ? JSON.stringify(data, null, 2) : "Deleted." }] }; });
}
