import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { retellGet, retellPost, retellDelete } from "../services/retell-client.js";
import { CHARACTER_LIMIT } from "../constants.js";
function truncate(t: string): string { return t.length <= CHARACTER_LIMIT ? t : t.slice(0, CHARACTER_LIMIT) + "\n\n... (truncated)"; }
export function registerKnowledgeBaseTools(server: McpServer): void {
  server.registerTool("retell_list_knowledge_bases", { title: "List Knowledge Bases", description: "List all knowledge bases.", inputSchema: {}, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async () => { const { data } = await retellGet("/list-knowledge-bases"); return { content: [{ type: "text", text: truncate(JSON.stringify(data, null, 2)) }] }; });
  server.registerTool("retell_get_knowledge_base", { title: "Get Knowledge Base", description: "Get a specific knowledge base.\n\nArgs:\n  - knowledge_base_id (string)", inputSchema: { knowledge_base_id: z.string().min(1) }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ knowledge_base_id }) => { const { data } = await retellGet(`/get-knowledge-base/${knowledge_base_id}`); return { content: [{ type: "text", text: truncate(JSON.stringify(data, null, 2)) }] }; });
  server.registerTool("retell_create_knowledge_base", { title: "Create Knowledge Base", description: "Create a new knowledge base.\n\nArgs:\n  - knowledge_base_name (string), enable_auto_refresh (boolean?)", inputSchema: { knowledge_base_name: z.string().min(1), enable_auto_refresh: z.boolean().optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false } }, async ({ knowledge_base_name, enable_auto_refresh }) => { const body: Record<string, unknown> = { knowledge_base_name }; if (enable_auto_refresh !== undefined) body.enable_auto_refresh = enable_auto_refresh; const { data } = await retellPost("/create-knowledge-base", body); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_add_knowledge_base_sources", { title: "Add KB Sources", description: "Add URL or text sources to a knowledge base.\n\nArgs:\n  - knowledge_base_id (string), sources (array of {type, url?, title?, content?})", inputSchema: { knowledge_base_id: z.string().min(1), sources: z.array(z.object({ type: z.enum(["url", "text"]), url: z.string().optional(), title: z.string().optional(), content: z.string().optional() })).min(1) }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true } }, async ({ knowledge_base_id, sources }) => { const { data } = await retellPost(`/add-knowledge-base-sources/${knowledge_base_id}`, { sources }); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_delete_knowledge_base_source", { title: "Delete KB Source", description: "Remove a source from a knowledge base.\n\nArgs:\n  - knowledge_base_id (string), source_id (string)", inputSchema: { knowledge_base_id: z.string().min(1), source_id: z.string().min(1) }, annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false } }, async ({ knowledge_base_id, source_id }) => { const { data } = await retellDelete(`/delete-knowledge-base-source/${knowledge_base_id}/${source_id}`); return { content: [{ type: "text", text: data ? JSON.stringify(data, null, 2) : "Source deleted." }] }; });
  server.registerTool("retell_delete_knowledge_base", { title: "Delete Knowledge Base", description: "Delete a knowledge base.\n\nArgs:\n  - knowledge_base_id (string)", inputSchema: { knowledge_base_id: z.string().min(1) }, annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false } }, async ({ knowledge_base_id }) => { const { data } = await retellDelete(`/delete-knowledge-base/${knowledge_base_id}`); return { content: [{ type: "text", text: data ? JSON.stringify(data, null, 2) : "Knowledge base deleted." }] }; });
}
