import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { retellGet, retellPost, retellPatch, retellDelete } from "../services/retell-client.js";
import { CHARACTER_LIMIT } from "../constants.js";
function truncate(t: string): string { return t.length <= CHARACTER_LIMIT ? t : t.slice(0, CHARACTER_LIMIT) + "\n\n... (truncated)"; }
export function registerLlmTools(server: McpServer): void {
  server.registerTool("retell_list_llms", { title: "List Retell LLMs", description: "List all Retell LLM response engine configs.", inputSchema: {}, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async () => { const { data } = await retellGet("/list-retell-llms"); return { content: [{ type: "text", text: truncate(JSON.stringify(data, null, 2)) }] }; });
  server.registerTool("retell_get_llm", { title: "Get Retell LLM", description: "Get a Retell LLM config.\n\nArgs:\n  - llm_id (string)", inputSchema: { llm_id: z.string().min(1) }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ llm_id }) => { const { data } = await retellGet(`/get-retell-llm/${llm_id}`); return { content: [{ type: "text", text: truncate(JSON.stringify(data, null, 2)) }] }; });
  server.registerTool("retell_create_llm", { title: "Create Retell LLM", description: "Create a new Retell LLM config.\n\nArgs:\n  - model (string?), general_prompt (string?), begin_message (string?), general_tools (array?), knowledge_base_ids (array?), inbound_dynamic_variables_webhook_url (string?)", inputSchema: { model: z.string().optional(), general_prompt: z.string().optional(), begin_message: z.string().optional(), general_tools: z.array(z.record(z.unknown())).optional(), knowledge_base_ids: z.array(z.string()).optional(), inbound_dynamic_variables_webhook_url: z.string().url().optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false } }, async ({ model, general_prompt, begin_message, general_tools, knowledge_base_ids, inbound_dynamic_variables_webhook_url }) => { const body: Record<string, unknown> = {}; if (model) body.model = model; if (general_prompt) body.general_prompt = general_prompt; if (begin_message) body.begin_message = begin_message; if (general_tools) body.general_tools = general_tools; if (knowledge_base_ids) body.knowledge_base_ids = knowledge_base_ids; if (inbound_dynamic_variables_webhook_url) body.inbound_dynamic_variables_webhook_url = inbound_dynamic_variables_webhook_url; const { data } = await retellPost("/create-retell-llm", body); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_update_llm", { title: "Update Retell LLM", description: "Update a Retell LLM config.\n\nArgs:\n  - llm_id (string), model (string?), general_prompt (string?), begin_message (string?), general_tools (array?), knowledge_base_ids (array?)", inputSchema: { llm_id: z.string().min(1), model: z.string().optional(), general_prompt: z.string().optional(), begin_message: z.string().optional(), general_tools: z.array(z.record(z.unknown())).optional(), knowledge_base_ids: z.array(z.string()).optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ llm_id, model, general_prompt, begin_message, general_tools, knowledge_base_ids }) => { const body: Record<string, unknown> = {}; if (model) body.model = model; if (general_prompt) body.general_prompt = general_prompt; if (begin_message) body.begin_message = begin_message; if (general_tools) body.general_tools = general_tools; if (knowledge_base_ids) body.knowledge_base_ids = knowledge_base_ids; const { data } = await retellPatch(`/update-retell-llm/${llm_id}`, body); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_delete_llm", { title: "Delete Retell LLM", description: "Delete a Retell LLM config.\n\nArgs:\n  - llm_id (string)", inputSchema: { llm_id: z.string().min(1) }, annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false } }, async ({ llm_id }) => { const { data } = await retellDelete(`/delete-retell-llm/${llm_id}`); return { content: [{ type: "text", text: data ? JSON.stringify(data, null, 2) : "Deleted." }] }; });
}
