import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { retellGet, retellPost, retellPatch, retellDelete } from "../services/retell-client.js";
import { CHARACTER_LIMIT } from "../constants.js";
function truncate(t: string): string { return t.length <= CHARACTER_LIMIT ? t : t.slice(0, CHARACTER_LIMIT) + "\n\n... (truncated)"; }
export function registerPhoneTools(server: McpServer): void {
  server.registerTool("retell_list_phone_numbers", { title: "List Phone Numbers", description: "List all phone numbers.", inputSchema: {}, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async () => { const { data } = await retellGet("/list-phone-numbers"); return { content: [{ type: "text", text: truncate(JSON.stringify(data, null, 2)) }] }; });
  server.registerTool("retell_get_phone_number", { title: "Get Phone Number", description: "Get phone number details.\n\nArgs:\n  - phone_number (string, E.164)", inputSchema: { phone_number: z.string().min(1) }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ phone_number }) => { const { data } = await retellGet(`/get-phone-number/${encodeURIComponent(phone_number)}`); return { content: [{ type: "text", text: truncate(JSON.stringify(data, null, 2)) }] }; });
  server.registerTool("retell_create_phone_number", { title: "Create Phone Number", description: "Purchase a new phone number.\n\nArgs:\n  - area_code (number?), inbound_agent_id (string?), outbound_agent_id (string?), nickname (string?), provider (string?), country_code (string?), toll_free (boolean?)", inputSchema: { area_code: z.number().int().optional(), inbound_agent_id: z.string().optional(), outbound_agent_id: z.string().optional(), nickname: z.string().optional(), provider: z.string().optional(), country_code: z.string().optional(), toll_free: z.boolean().optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true } }, async ({ area_code, inbound_agent_id, outbound_agent_id, nickname, provider, country_code, toll_free }) => { const body: Record<string, unknown> = {}; if (area_code !== undefined) body.area_code = area_code; if (inbound_agent_id) body.inbound_agent_id = inbound_agent_id; if (outbound_agent_id) body.outbound_agent_id = outbound_agent_id; if (nickname) body.nickname = nickname; if (provider) body.provider = provider; if (country_code) body.country_code = country_code; if (toll_free !== undefined) body.toll_free = toll_free; const { data } = await retellPost("/create-phone-number", body); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_update_phone_number", { title: "Update Phone Number", description: "Update a phone number config.\n\nArgs:\n  - phone_number (string), inbound_agent_id (string?), outbound_agent_id (string?), nickname (string?)", inputSchema: { phone_number: z.string().min(1), inbound_agent_id: z.string().optional(), outbound_agent_id: z.string().optional(), nickname: z.string().optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ phone_number, inbound_agent_id, outbound_agent_id, nickname }) => { const body: Record<string, unknown> = {}; if (inbound_agent_id !== undefined) body.inbound_agent_id = inbound_agent_id; if (outbound_agent_id !== undefined) body.outbound_agent_id = outbound_agent_id; if (nickname) body.nickname = nickname; const { data } = await retellPatch(`/update-phone-number/${encodeURIComponent(phone_number)}`, body); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_delete_phone_number", { title: "Delete Phone Number", description: "Delete a phone number.\n\nArgs:\n  - phone_number (string)", inputSchema: { phone_number: z.string().min(1) }, annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false } }, async ({ phone_number }) => { const { data } = await retellDelete(`/delete-phone-number/${encodeURIComponent(phone_number)}`); return { content: [{ type: "text", text: data ? JSON.stringify(data, null, 2) : "Deleted." }] }; });
}
