import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { retellGet, retellPost } from "../services/retell-client.js";
import { CHARACTER_LIMIT } from "../constants.js";
function truncate(t: string): string { return t.length <= CHARACTER_LIMIT ? t : t.slice(0, CHARACTER_LIMIT) + "\n\n... (truncated)"; }
export function registerVoiceTools(server: McpServer): void {
  server.registerTool("retell_list_voices", { title: "List Voices", description: "List all available voices (built-in + custom).", inputSchema: {}, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async () => { const { data } = await retellGet("/list-voices"); return { content: [{ type: "text", text: truncate(JSON.stringify(data, null, 2)) }] }; });
  server.registerTool("retell_get_voice", { title: "Get Voice", description: "Get voice details.\n\nArgs:\n  - voice_id (string)", inputSchema: { voice_id: z.string().min(1).describe("Voice ID") }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ voice_id }) => { const { data } = await retellGet(`/get-voice/${voice_id}`); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_search_voice", { title: "Search Voice", description: "Search voices by gender, accent, age, provider, keyword.", inputSchema: { gender: z.enum(["male", "female"]).optional(), accent: z.string().optional(), age: z.string().optional(), provider: z.string().optional(), keyword: z.string().optional() }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true } }, async ({ gender, accent, age, provider, keyword }) => { const body: Record<string, unknown> = {}; if (gender) body.gender = gender; if (accent) body.accent = accent; if (age) body.age = age; if (provider) body.provider = provider; if (keyword) body.keyword = keyword; const { data } = await retellPost("/search-voice", body); return { content: [{ type: "text", text: truncate(JSON.stringify(data, null, 2)) }] }; });
  server.registerTool("retell_clone_voice", { title: "Clone Voice", description: "Clone a voice from audio URL.\n\nArgs:\n  - voice_name (string), audio_url (string)", inputSchema: { voice_name: z.string().min(1), audio_url: z.string().url() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true } }, async ({ voice_name, audio_url }) => { const { data } = await retellPost("/clone-voice", { voice_name, audio_url }); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
  server.registerTool("retell_add_voice", { title: "Add Voice", description: "Import a third-party voice.\n\nArgs:\n  - voice_name (string), provider (string), provider_voice_id (string)", inputSchema: { voice_name: z.string().min(1), provider: z.string().min(1), provider_voice_id: z.string().min(1) }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true } }, async ({ voice_name, provider, provider_voice_id }) => { const { data } = await retellPost("/add-voice", { voice_name, provider, provider_voice_id }); return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] }; });
}
